/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'cakes' : null } |
  { 'fastFood' : null } |
  { 'pastries' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : string,
}
export interface SiteSettings { 'tagline' : string, 'aboutText' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getMenuItemsByCategory' : ActorMethod<[Category], Array<MenuItem>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];